ScheduleIntervalTime: 500
Writable:
    LogLevel: INFO
Service:
    Host: support-scheduler.edgex.ziti
    Port: 80
    StartupMsg: "This is the Support Scheduler Microservice"
    SecurityOptions:
        ListenMode: "zerotrust"
        OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
        OpenZitiServiceName: "edgex.support-scheduler"
Intervals:
    Midnight:
        Name: midnight
        Start: 20180101T000000
        Interval: 24h
IntervalActions:
    ScrubAged:
        Name: scrub-aged-events
        Host: localhost
        Port: 59880
        Protocol: http
        Method: DELETE
        Path: /api/v2/event/age/604800000000000   # Remove events older than 7 days
        Interval: midnight
        AdminState: UNLOCKED
        AuthMethod: JWT     # AuthMethod = JWT degrades to no auth in security-disabled EdgeX

MessageBus:
  Optional:
    ClientId: support-scheduler

Database:
  Name: scheduler

