Writable:
  LogLevel: INFO
  ResendLimit: 2
  ResendInterval: 5s
  InsecureSecrets:
    SMTP:
      SecretName: smtp
      SecretData:
        username: username@mail.example.com
        password: ''
Service:
  Host: support-notifications.edgex.ziti
  Port: 59860
  StartupMsg: "This is the Support Notifications Microservice"
  SecurityOptions:
    ListenMode: "zerotrust"
    OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
    OpenZitiServiceName: "edgex.support-notifications"
Smtp:
  Host: my.email.server
  Port: 587
  Sender: some.email.address
  EnableSelfSignedCert: false
  Subject: EdgeX Notification
  # SecretName is used to specify the secret name to store the credential(username and password) for connecting the SMTP server
  # User need to store the credential via the /secret API before sending the email notification
  SecretName: smtp
  # AuthMode is the SMTP authentication mechanism. Currently, "usernamepassword" is the only AuthMode supported by this service, and the secret keys are "username" and "password".
  AuthMode: usernamepassword

MessageBus:
  Optional:
    ClientId: support-notifications

Database:
  Name: notifications

