Writable:
  LogLevel: INFO
  ProfileChange:
    StrictDeviceProfileChanges: false
    StrictDeviceProfileDeletes: false
  UoM:
    Validation: false
Service:
  Host: localhost
  Port: 59105
  StartupMsg: "This is the EdgeX Core Metadata Microservice"
  SecurityOptions:
    ListenMode: "zerotrust"
    OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
    OpenZitiServiceName: "edgex.core-metadata"
UoM:
  UoMFile: ./res/uom.yaml

MessageBus:
  Optional:
    ClientId: core-metadata

Database:
  Name: metadata

