MaxEventSize: 25000 # Defines the maximum event size in kilobytes
Writable:
  LogLevel: "INFO"
  PersistData: true
  Telemetry:
    Metrics: # All service's metric names must be present in this list.
      EventsPersisted: false
      ReadingsPersisted: false
#    Tags: # Contains the service level tags to be attached to all the service's metrics
    ##    Gateway="my-iot-gateway" # Tag must be added here or via Consul Env Override can only change existing value, not added new ones.
Service:
  Port: 59880
  Host: "localhost14"
  StartupMsg: "This is the Core Data Microservice"
  ListenMode: "zerotrust"
  ListenOptions:
    OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
    OpenZitiServiceName: "edgex.core-data"

  SecretStore:
    Type: vault
    Protocol: http
    Host: localhostb

MessageBus:
  Optional:
    ClientId: "core-data"

Database:
  Name: "coredata"

SecretStore:
  Type: vault
  Protocol: http
  Host: localhosta